version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: node_backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "3001:3000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user_password
      - DATABASE_NAME=my_database
      - DATABASE_PORT=3307

volumes:
  mysql_data:
